### ISSUE TITLE
Invalid parameter: 'response_format' when using Azure OpenAI

### ISSUE THREAD

**Issue by vicdotdevelop** [mrwadams/stride-gpt#19]
When using Azure OpenAI i get the following error:

```
Error generating threat model after 3 attempts: Error code: 400 - {'error': {'message': "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}
```

I just used the example prompt from the left pane and left all settings as it is.
Models I tried from my Azure OpenAI instance: gpt-4 & gpt3.5-turbo. Both resulted in the same error.

**Comment by mrwadams** [comment]
Closing this as I haven't heard anything more.
