### ISSUE TITLE
openAI API - error code 404

### ISSUE THREAD

**Issue by AlenKrga** [mrwadams/stride-gpt#21]
Hi @mrwadams,

Please could you help me, I'm facing some issues with trying app.
I tried to use OpenAI API option, after following steps to enter OpenAI API key. 
Entered API key (using paid version of chatGPT).
Using Example Application description. After clicking on Threat Model I get this error:
`Error generating threat model after 3 attempts: Error code: 404 - {'error': {'message': 'The model gpt-4o does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}`

I'm facing error with gpt-4o, gpt-4-turbo and couldn't try other versions as text field to enter information is missing.

Thanks in advance

**Comment by mrwadams** [comment]
Hi,

Using the paid version of ChatGPT isn't the same as having the ability to use the OpenAI API.

You need to add a payment method under platform.openai.com and add a small amount of credit. After that you'll be able to use an API key.


Matt
