### ISSUE TITLE
Request for AMD64 Compatible Docker Image

### ISSUE THREAD

**Issue by frankwiersma** [mrwadams/stride-gpt#24]
I recently tried to pull and run the mrwadams/stridegpt:latest Docker image on my AMD64 architecture machine. However, I encountered an architecture mismatch issue. The image appears to be built for ARM64 architecture, which leads to an "exec format error" when running it on an AMD64 host.

Here are the steps I followed:

Pulled the latest Docker image:

`docker pull mrwadams/stridegpt:latest`
Tried to run the Docker container:

`docker run -p 8501:8501 mrwadams/stridegpt`

Encountered the following error:

`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /usr/local/bin/streamlit: exec format error`

Would it be possible to provide an AMD64 compatible version of the Docker image? This would greatly help users running on AMD64 architecture to use stridegpt without needing to set up QEMU for emulation.

Thank you for your assistance!

Best regards,

**Comment by mrwadams** [comment]
Hi @frankwiersma,

I've added a `v0.8-amd` image to Docker Hub. Please try it out and let me know how you get on.

`docker run -p 8501:8501 mrwadams/stridegpt:v0.8-amd`
