### ISSUE TITLE
Add local LLM hosting option

### ISSUE THREAD

**Issue by willasaywhat** [mrwadams/stride-gpt#25]
I forked the repository and added support for a custom OpenAI compatible endpoint using LM Studio. This allows you to run a local LLM and generate threat modeling artifacts through the tool without sharing data with a 3rd party. Happy to put in a pull request, but still testing on my end.

Mistral 7B performs relatively well here, but I am seeing some issues with the mermaid output not being escaped properly and the Gherkin test case generation is failing on return. Not sure why, but otherwise... it works pretty great.

**Comment by saurabhlime** [comment]
This would be great if we could upload the artifacts to a Github repo where this resides a living threat model to be included in a change management process

**Comment by willasaywhat** [comment]
Submitted #37 in support of this idea.

**Comment by mrwadams** [comment]
Hi @willasaywhat,

I've added support for running local models using Ollama in the [v0.9-beta](https://github.com/mrwadams/stride-gpt/tree/v0.9-beta) branch. Please check it out and let me know what you think.

I recommend trying Gemma 2 9B for generating Attack Trees. It seems to do very well with writing syntactically correct Mermaid.

**Comment by willasaywhat** [comment]
This seems to work relatively well. My only concern here is that the URI and port are not customizable. Gemma2 9b does seem to work pretty well, though. Thanks for implementing this!
