### ISSUE TITLE
Combining architecture diagram and security requirements / application description?

### ISSUE THREAD

**Issue by kimsyversen** [mrwadams/stride-gpt#29]
First of all, this is a great initiative. I think all developer teams can save a lot of time and find security more pleasurable to work with if they use this tool. 

I have tested it using the gpt4-o model and when I upload the architecture diagram it seems to override the description of the application. In threat modelling we should focus on the threats that matter and I think the output can be even better.  

To make it better,  I think it should be possible to upload both an architecture diagram and provide your own description of the application or add your own security requirements:

- Some developer teams might use a developer platform which already have many security measures built in. This could be a set of policies that ensures a super secure configuration of storage accounts or a policies that ensures all data both in rest and in motion are encrypted.
- Other teams might get a list of security requirements from the security department, often a Excel document with requirements of the more generic type such as "All data shall be encrypted" and it might be difficult implement this 100%.

Would love to hear what others think about this.

**Comment by mrwadams** [comment]
Hi @kimsyversen,

Thanks for the feedback. Try uploading the architecture diagram first and then updating the application description to add any extra details you want to include.

You can add existing security controls into the application description to provide the model with more context to the system design.
