### ISSUE TITLE
Can you replace with own LLM?

### ISSUE THREAD

**Issue by priyanka-raghavan-maersk** [mrwadams/stride-gpt#3]
Hi @mrwadams would it be possible to replace the open AI's LLM with custom instance of LLM?

**Comment by mrwadams** [comment]
Hi @priyanka-raghavan-maersk,

Yes, although I don't intend to make that change in this project. Using a different LLM would likely require significant changes to the prompt templates and output parsing in order to achieve equivalent and consistent results compared to using the OpenAI models.
