### ISSUE TITLE
Invalid parameter: 'response_format' when using Google AI API

### ISSUE THREAD

**Issue by Tarun-939** [mrwadams/stride-gpt#39]
I'm having trouble using the Google AI API. I'm getting the following error message: 

`"Error generating threat model after 3 attempts: Error code: 400 - {'error': {'message': "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}"`

I've created an API key and used it. Can you help me with selecting the AI model as Gemini 1.5 Pro in Google Studio?

**Comment by mrwadams** [comment]
Hi @Tarun-939 ,

The updates that Google have made to the Gemini 1.5 Pro model seem to have resolved this. I'm able to use the model with no issue.

<img width="1350" alt="Screenshot 2024-09-17 at 16 55 27" src="https://github.com/user-attachments/assets/278d8340-8af1-44b7-b380-1b44e1ee9f2d">
