### ISSUE TITLE
Exec format error on Ubuntu

### ISSUE THREAD

**Issue by reglorious** [mrwadams/stride-gpt#40]
Getting error below on Ubuntu 22.04.4 LTS

santosh@supercomp:~/code/stride-gpt$ docker run -p 8501:8501 mrwadams/stridegpt
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/local/bin/streamlit: exec format error

**Comment by mrwadams** [comment]
Hi @reglorious,

You need to specify the amd64 image when pulling from Docker.

`docker pull mrwadams/stridegpt:v0.8.1-amd64`
