### ISSUE TITLE
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

### ISSUE THREAD

**Issue by AnahatM** [mrwadams/stride-gpt#42]
Unmodified install of the code is throwing this error, on multiple systems with every requirement installed, after doing `streamlit run main.py`:

 `File "C:\Dev\stride-gpt-master\venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Dev\stride-gpt-master\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
File "C:\Dev\stride-gpt-master\main.py", line 7, in <module>
    from threat_model import create_threat_model_prompt, get_threat_model, get_threat_model_azure, get_threat_model_google, get_threat_model_mistral, json_to_markdown, get_image_analysis, create_image_analysis_prompt
File "C:\Dev\stride-gpt-master\threat_model.py", line 7, in <module>
    from mistralai.models.chat_completion import ChatMessage`

![image](https://github.com/user-attachments/assets/7fcd8891-2617-4da1-b07c-2e60ccc91934)

**Comment by mrwadams** [comment]
Hi @AnahatM,

Are you installing the modules individually or running `pip install -r requirements.txt`?

I'd also recommend trying a fresh virtual environment.

**Comment by AnahatM** [comment]
Thanks for the response. I did both those things, `pip install -r requirements.txt` and new venv, and also re-installed python. It runs fine on docker, the local version also runs if you disable all the mistral features.

**Comment by mrwadams** [comment]
Looks like it's because Mistrail have made some breaking changes when introducing v1.x of their Python SDK (https://github.com/mistralai/client-python/blob/main/MIGRATION.md).

As a temporary fix you could pin the dependency to an earlier version. I'll look at the required updates this evening.
